# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170816_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
